'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Chat from "./components/menu/chat"
import Rules from "./components/menu/rules"
import Speachbubble from './components/speachbubble'
import Rewards from './components/menu/rewards'
import Ranking from './components/menu/ranking'
import SpeachBubbleContextProvider from './contexts/speachBubbleContext'
import Login from './components/menu/login'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Big Baba Bubu Advent Calendar',
  description: 'Generated by the Macher',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <SpeachBubbleContextProvider>
          <header className='flex fixed w-screen flex-col top-5'>
            <div className='flex flex-row h-20'>
              <div className='flex justify-between w-11/12'>
                <div className='flex w-1/4 justify-around'>
                  <Rewards />
                  <Ranking />
                </div>
                <div className='flex w-1/4 justify-around'>
                  <Chat />
                  <Rules />
                </div>
              </div>
              <Login />
            </div>
            <div className='flex flex-col w-11/12'>
              <Speachbubble />
            </div>
          </header>
        </SpeachBubbleContextProvider>
        <main> {children} </main>
      </body>
    </html>
  )
}