import { AnimationTypesProps } from "./typesForSprites";


export function allAnimationSpritesProps(ctx: CanvasRenderingContext2D): AnimationTypesProps[] {
    return [
        {
            lights: [
                {
                    position: { x: 100, y: 100 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/CandleSheet.png',
                    scale: 0.5,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 5,
                    animationFrames: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }],
                    repeatAnimation: true,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 5, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 130, y: 100 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/CandleSheet.png',
                    scale: 0.5,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 5,
                    animationFrames: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }],
                    repeatAnimation: true,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 5, y: 0 },
                    moveProps: null

                }
            ],
            doors: [
                {
                    position: { x: 500, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 1, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 425, y: (ctx.canvas.height - 622) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 2, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 950, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 3, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 350, y: (ctx.canvas.height - 456) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 4, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 650, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 5, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 275, y: (ctx.canvas.height - 290) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 6, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 875, y: (ctx.canvas.height - 290) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 7, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 200, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 8, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 650, y: (ctx.canvas.height - 456) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 9, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 800, y: (ctx.canvas.height - 456) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 10, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 275, y: (ctx.canvas.height - 622) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 11, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 575, y: (ctx.canvas.height - 622) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 12, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 1025, y: (ctx.canvas.height - 290) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 13, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 425, y: (ctx.canvas.height - 290) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 14, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 725, y: (ctx.canvas.height - 622) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 15, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 575, y: (ctx.canvas.height - 290) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 16, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 500, y: (ctx.canvas.height - 456) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 17, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 875, y: (ctx.canvas.height - 622) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 18, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 200, y: (ctx.canvas.height - 456) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 19, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 950, y: (ctx.canvas.height - 456) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 20, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 800, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 21, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 1025, y: (ctx.canvas.height - 622) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 22, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 725, y: (ctx.canvas.height - 290) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 23, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 350, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 24, color: "black", size: 32, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                }
            ],
            items: [

            ],
            traps: [],
            treasures: []
        },
        {
            lights: [
                {
                    position: { x: 100, y: 100 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/CandleSheet.png',
                    scale: 0.5,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 5,
                    animationFrames: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }],
                    repeatAnimation: true,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 5, y: 0 },
                    moveProps: null
                },
                {
                    position: { x: 130, y: 100 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/CandleSheet.png',
                    scale: 0.5,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 5,
                    animationFrames: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }],
                    repeatAnimation: true,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 5, y: 0 },
                    moveProps: null
                },
            ],
            doors: [
                {
                    position: { x: 1025, y: (ctx.canvas.height - 124) },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/WoodDoorSheet.png',
                    scale: 1,
                    maxFrames: 6,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }, { x: 5, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 0, color: "black", size: 16, yOffset: 45},
                    hitBoxOffset: { x: 20, y: 30, width: 40, height: 60 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                }
            ],
            items: [

            ],
            traps: [
                {
                    position: { x: 300, y: ctx.canvas.height - 20 },
                    ctx: ctx,
                    imageSrc: './Questionmark.png',
                    scale: 0.3,
                    maxFrames: 1,
                    maxAnimations: 1,
                    frameRate: 10,
                    animationFrames: [{ x: 0, y: 0 }],
                    repeatAnimation: false,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: { velocityX: 1, velocityY: 0, rangeX: 100, rangeY: 0 }
                },
                {
                    position: { x: 600, y: 690 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/candyBarTrap.png',
                    scale: 1,
                    maxFrames: 1,
                    maxAnimations: 1,
                    frameRate: 1000,
                    animationFrames: [{ x: 0, y: 0 }],
                    repeatAnimation: false,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: { velocityX: 0, velocityY: 0, rangeX: 0, rangeY: 0 }
                },
                {
                    position: { x: 630, y: 690 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/candyBarTrap.png',
                    scale: 1,
                    maxFrames: 1,
                    maxAnimations: 1,
                    frameRate: 1000,
                    animationFrames: [{ x: 0, y: 0 }],
                    repeatAnimation: false,
                    startStatic: false,
                    dayNumber: {isDisplayed: false, value: -1, color: "black", size: 0, yOffset: 0},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: { velocityX: 0, velocityY: 0, rangeX: 0, rangeY: 0 }
                },
            ],
            treasures: [
                {
                    position: { x: 325, y: 460 },
                    ctx: ctx,
                    imageSrc: './SpriteSheets/treasureSprite.png',
                    scale: 2,
                    maxFrames: 4,
                    maxAnimations: 1,
                    frameRate: 20,
                    animationFrames: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }],
                    repeatAnimation: false,
                    startStatic: true,
                    dayNumber: {isDisplayed: true, value: 1, color: "black", size: 16, yOffset: 15},
                    hitBoxOffset: { x: 0, y: 0, width: 0, height: 0 },
                    staticFrame: { x: 0, y: 0 },
                    moveProps: null
                }
            ]
        }
    ]
}